# A minimal left prompt
format = """$directory$git_branch$git_status$character"""

# # move the rest of the prompt to the right
right_format = """$all"""

[character]
format = "[â¯](bold red)[â¯](bold yellow)[â¯](bold green) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 1
truncate_to_repo = true
truncation_symbol = ''

[cmd_duration]
disabled = true

[status]
disabled = false
symbol = 'ï€ '

[git_branch]
symbol = "ï˜ "
truncation_length = 20
truncation_symbol = "â€¦"
style="bold purple"

[aws]
disabled = true

[gcloud]
disabled = true

[docker_context]
symbol = "ïŒˆ "

[package]
disabled = true

[java]
disabled = true

[golang]
symbol = "î˜§ "

[guix_shell]
symbol = "ïŒ¥ "

[lua]
symbol = "î˜  "

[nix_shell]
symbol = "ïŒ“ "

[python]
symbol = "îˆµ "

[rust]
symbol = "ğŸ¦€ "
